on:
 #push:
 workflow_dispatch:   

jobs:
    DEV:
      runs-on: ubuntu-latest
      environment: DEV  

      steps:
        - uses: actions/checkout@v3
        - name: running Script
          run: |
             echo "Job runs For .DEV envirment"


    QA:
        runs-on: ubuntu-latest
        environment: QA   
        needs: DEV 
  
        steps:
          - uses: actions/checkout@v3
          - name: running Script
            run: |
               echo "Job runs For .QA envirment"  
                         
    PROD:
        runs-on: ubuntu-latest
        environment: PROD   
        needs: QA 
  
        steps:
          - uses: actions/checkout@v3
          - name: running Script
            run: |
               echo "Job runs For .PROD envirment"      
               
               

               